import Head from "next/head";
import { useState, useEffect } from "react";
import { Card,Form,} from "react-bootstrap";
import axios, * as others from "axios";

function Home() {
  const [allEntries, setAllentries] = useState([]);
  const [category, setCategory] = useState([]);
  const [display,setDisplay]=useState([])
  let originalAr = [];


  function populateData() {
    axios
      .get(`https://api.publicapis.org/entries`)
      .then((response) => {
        setAllentries(response.data.entries);
        setDisplay(response.data.entries)
        console.log(allEntries);
       
      })
      .catch((error) => {
        console.log(error);
      });
  }

  function getCategory(e) {
    axios
      .get(`https://api.publicapis.org/categories`)
      .then((response) => {
        console.log(response.data);
        setCategory(response.data.categories);
      })
      .catch((error) => {
        console.log(error);
      });
  }

  function filterbyCategory(e) {
    axios
      .get(`https://api.publicapis.org/entries?category=${e.target.value}`)
      .then((response) => {
        // setAllentries(response.data.entries);
        setDisplay(response.data.entries);
      })

      .catch((error) => {
        console.log(error);
      });
  }

  function searchCors(e) {
    console.log(originalAr);
    originalAr=allEntries.map((elem)=>{
      return({...elem})
    })
    if (e.target.value == "yes") {
      let result = originalAr.filter((el) => el.Cors == e.target.value).map((ele)=>{
        return({...ele})
      });
      console.log(result);
      setDisplay(result);

    } else if (e.target.value == "no") {
      let result = originalAr.filter((el) => el.Cors == e.target.value).map((ele)=>{
        return({...ele})
      });;
      console.log(result);
      setDisplay(result);

    }else if (e.target.value == "all") {
      populateData()
    }
  }

  useEffect(() => {
    populateData();
    getCategory();
  }, []);

  return (

    <div className="layout">
      <Head>
        <title>TrellisysTask</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <section className="container-fluid">

          <div className="container-fluid navmenu row w-100 m-auto py-2 bg-dark" >

            <Form.Group  className='col-lg-3 col-6' controlId="validationCustom02">
              <Form.Select className="w-100"
                    name="cate"
                    onChange={
                      filterbyCategory}>

                    <option value="">Select By Category</option>
                    {category.map((data) => {
                      return <option key={data.id}  value={data}>{data}</option>;
                    })}

              </Form.Select>
            </Form.Group>

            <Form.Group  className='col-lg-3 col-6' controlId="validationCustom02">
              <Form.Select
                    className="w-100"
                    placeholder="Search cors Yes Or No..."
                    onChange={
                      searchCors
                    }>
                    <option value="">Filter by cors</option>
                    <option value="all">All</option>
                    <option value="yes">Yes</option>
                    <option value="no">No</option>
              </Form.Select>
           </Form.Group>
          </div>

          <div className="container-fluid card_box m-auto">

              <div className="container-fluid cardss row w-100 m-auto my-2">

                {display.map((data) => {
                  return (
                    <Card key={data.id}className=" populate container-fluid  col-lg-2 my-3 mx-2 p-2">
                          <h6>Category:{data.Category}</h6>
                          <p>API:{data.API}</p>
                          <p>Auth:{data.Auth}</p>
                          <p>Cors:{data.Cors}</p>
                          <p>Description:{data.Description}</p>
                    </Card>
                  );
                })}

              </div>

          </div>
        </section>
    </div>
  );
}
export default Home;
